# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: psqluser
  password: changeit
  host: localhost
  port: 5432

development:
  <<: *default
  database: alpha-development

test:
  <<: *default
  database: alpha-test

production:
  <<: *default
  database: alpha-production
  username: alpha-blog
  password: <%= ENV['ALPHA-BLOG_DATABASE_PASSWORD'] %>
